### ISSUE TITLE
Feedback (EventID, Configuration)

### ISSUE THREAD

**Issue by W357** [manigandham/serilog-sinks-googlecloudlogging#1]
Hi Mani. 
First of all, thanks for this project. Good Job! After a while playing with this I have some feedback:
1) Handling of EventIDs. e.g.  _logging.LogDebug(eventId: 1, message: "Debug") will throw an exception in GoogleCloudLoggingSink.cs line 65.
2) Took me a while to figure out thats its not possible to create custom log ressources. Using the default (global) now. Maybe worth to mention in the documentation that this are the supported ressources: https://cloud.google.com/logging/docs/api/v2/resource-list
3) It would be great to add support to setting up the sink in the appconfig.json using Serilog.Settings.Configuration

Thanks
Simon

**Comment by manigandham** [comment]
Hey @W357, thanks for reporting.

It looks like the built-in .NET Core logger abstraction uses child properties so `eventId` is written as `{ Id: 1 }` which was unhandled. This has been fixed and will be logged with the parent key prepended so the label should read: `EventId.Id: 1` in GCP logs.

Updated the documentation. Will look into the appconfig.json support in a separate issue.

Nuget should be updated: https://www.nuget.org/packages/Serilog.Sinks.GoogleCloudLogging/1.1.0

**Comment by W357** [comment]
Cool. Appreciate the update!
