### ISSUE TITLE
EmitBatchAsync() fails to write log messages

### ISSUE THREAD

**Issue by slolife** [manigandham/serilog-sinks-googlecloudlogging#11]
EmitBatchAsync() call fails to write anything when `await _client.WriteLogEntriesAsync(_logNameToWrite, _resource, _sinkOptions.Labels, logEntries);` is called.  What is the best way to debug what is happening?

**Comment by slolife** [comment]
I don't know what is working, but I have checked that the service account has "Logs Writer" permission and that the project ID is correct.  I'll try the test project and report back.

**Comment by manigandham** [comment]
@slolife Did you get this figured out?

**Comment by slolife** [comment]
No, but I think it is going to be a misconfiguration on my part.  We can close this and I'll open a new one if/when I get more real data and information to present. Thank you
