### ISSUE TITLE
Log name stays source context even when UseSourceContextAsLogName is set to false

### ISSUE THREAD

**Issue by yosigolan** [manigandham/serilog-sinks-googlecloudlogging#12]
Hey.
when i set a log name like "BasicService" and set UseSourceContextAsLogName to false the log name stays the source context. more over in the github project read me you write: "When using default options, logs will appear under these filter settings:" and then show log name default. but the default value of UseSourceContextAsLogName is true so it dont seems right.

Thanks

**Comment by manigandham** [comment]
I've updated the readme, and ran the test project which shows the settings working fine.

Can you run the TestWeb project on your end and see if it works correctly?

**Comment by yosigolan** [comment]
Thank you for the reply.
i will try it and update.

**Comment by yosigolan** [comment]
i dont understand, the testweb project does not use the appsettings configuration and in the code it does not set the UseSourceContextAsLogName to false. meaning it will write the log name as source context. what am i missing?

**Comment by manigandham** [comment]
Ah, the appsettings.json only supports `projectId` and `useJsonOutput` as it was a contributed change: https://github.com/manigandham/serilog-sinks-googlecloudlogging/pull/10

I'll make that clear in the readme too. Meanwhile I suggest creating the config in your code instead so you can use all the settings, or another pull request to handle all the settings would be appreciated.

**Comment by yosigolan** [comment]
i just saw this in the docs: "This only supports projectId and useJsonOutput settings."
does this means that i cant use the file config if i want to change the log name (i cant mix configurations right?)

**Comment by manigandham** [comment]
It won't work from appsettings.json.

**Comment by yosigolan** [comment]
i understand. got it to work from code.
thanks

**Comment by manigandham** [comment]
All the options can be set via `appsettings.json` now with version 1.7.0: https://github.com/manigandham/serilog-sinks-googlecloudlogging/blob/master/CHANGELOG.md
