### ISSUE TITLE
Question: is it possible to log under the resource of app engine and under my specific version id?

### ISSUE THREAD

**Issue by yosigolan** [manigandham/serilog-sinks-googlecloudlogging#13]
i dont find any documentation on how to log into different resources other than global.
is it possible to log into existing resource other than global?

**Comment by manigandham** [comment]
The readme links to this page: https://cloud.google.com/logging/docs/api/v2/resource-list

You can select the resource type name you need from that table. `gae_app` seems to be what you're looking for if you want it under App Engine. You'll need to add the appropriate labels as well to your logs for module and version.

**Comment by manigandham** [comment]
You can create the logging config programmatically when your app starts and set the details there. How you do that is up to you, I don't use GAE but there's probably a way for the app to read it's current service and version details.

**Comment by yosigolan** [comment]
you are right.
i managed to use the following environment variables:
`
  string serviceId = enviormentVariablesConfig["GAE_SERVICE"];
  string versionId = enviormentVariablesConfig["GAE_VERSION"];
`
works like charm.

Thanks
