### ISSUE TITLE
Exception is not part of the log

### ISSUE THREAD

**Issue by yosigolan** [manigandham/serilog-sinks-googlecloudlogging#14]
Hey.
when i log exceptions using serilog syntax i cant find them in the log attributes (in google viewer). do i need to add some label for them to appear?

Thanks Yosi

**Comment by manigandham** [comment]
I don't know. Properties attached to the logs show up so you'll have to debug it and see what's being sent. Exceptions aren't automatically handled by Serilog, you should add a helper like this to copy all the details: https://github.com/RehanSaeed/Serilog.Exceptions

**Comment by yosigolan** [comment]
Thanks, that solved it.

Yosi

**Comment by kooboo-binbin** [comment]
When I use Serilog Console, I can see the exception title.
 but I can't see any exception information in google viewer

**Comment by manigandham** [comment]
@kooboo-binbin Can you create a new issue and explain how youre logging the exception and what page in the GCP console you're viewing?

**Comment by kooboo-binbin** [comment]
@manigandham I just check the code I find I did not config errorReportingServiceName

**Comment by manigandham** [comment]
@kooboo-binbin Can you make a new issue please?
