### ISSUE TITLE
When Log level is critical, the exception is not added to json fileds.

### ISSUE THREAD

**Issue by kooboo-binbin** [manigandham/serilog-sinks-googlecloudlogging#19]
GoogleCloudLoggingSink.cs  line67 :if (_errorReportingEnabled && entry.Severity == LogSeverity.Error && e.Exception != null)

**Comment by manigandham** [comment]
Fixed in https://github.com/manigandham/serilog-sinks-googlecloudlogging/commit/c2d3ea196052b492e36bdd3652ef78ad1a260d32

**Comment by kooboo-binbin** [comment]
@manigandham  thanks. when will the new code be published to Nuget?

**Comment by manigandham** [comment]
Sorry about the delay, the latest 2.0.0 is released: https://www.nuget.org/packages/Serilog.Sinks.GoogleCloudLogging/2.0.0
