### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by nbelley** [manigandham/serilog-sinks-googlecloudlogging#21]
If I use as is the provided sample on the project site, it's not working in Xamarin, ReadFrom seems to be a readonly property:

https://i.imgur.com/hdmhwPV.png

**Comment by nbelley** [comment]
This was fixed using Serilog.COnfiguration nuget package. 

But, it seems pretty hard to make this work on Xamarin android. Is it possible?

**Comment by manigandham** [comment]
Are you saying it works then?

I don't use Xamarin so I don't know about that. You can always use the programmatic configuration though, and read the settings from `IConfiguration` yourself.

**Comment by nbelley** [comment]
ReadFrom is working, but I had to add another nuget package for it to work. But, getting the logger to work is not an easy task. Now it compiles, I can load the json config into a string and configure manually the sink, no more exceptions everyone seems happy, but nothing gets uploaded to stackdriver.

**Comment by manigandham** [comment]
Download this repo source code and run the TestWeb project to make sure your GCP account is setup correctly and can see the logs. Then try hardcoding the config in your app and running it that way.

**Comment by nbelley** [comment]
The logging is working from our regular apps, we are trying for the first time on our android app. I will try to use the Google.Cloud.Logging.V2 with Android to see if it works.

**Comment by manigandham** [comment]
@nbelley 
Did you get this figured out?
