### ISSUE TITLE
[Suggestion] Add the log message format as a property so that entire classes of message can be filtered out

### ISSUE THREAD

**Issue by baronfel** [manigandham/serilog-sinks-googlecloudlogging#23]
One thing that Logary's StackDriver integration did that I had some workflows around was writing the original message format before formatting to the log entry in a well-known field. For example `OriginalFormat` or `template`. This allowed for filtering in/out based on the format, which is a nice way to filter out entire classes of log messages from your view, at the cost of inflating the size of the message payload. Would this be an acceptable enhancement if it was hidden behind a configuration flag?

**Comment by manigandham** [comment]
Sure, send PR and we can add it in.

**Comment by baronfel** [comment]
Cool, I'll do just that. What's your opinion on what the new log property field should be called?  A few options I've been bouncing around:

* OriginalFormat - this is nice because it's in line with what the format value is called in the Asp.Net Core Logging wrapper
* MessageTemplate - this is more in line with Serilog's internal representation of the data

**Comment by manigandham** [comment]
I recommend using a string property and checking for null. That leaves it up to the user to pick whatever they choose. This is how the `ServiceName` property is currently configured.

**Comment by baronfel** [comment]
The downside with that approach is the potential duplication of data in that case, given that the Microsoft.Extensions.Logging infrastructure will always provide the OriginalFormat property.

**Comment by manigandham** [comment]
Got it, Seems like that would be the most common scenario anyway so this works. I'll merge soon.
