### ISSUE TITLE
Warning type not in log

### ISSUE THREAD

**Issue by bradsharp54** [manigandham/serilog-sinks-googlecloudlogging#27]
I've got to be doing something wrong, but I have logging setup exactly.  The program is running on a VM and I see logs being written. 

To test it, I put 

 _logger.LogWarning("warning {test}","dfd");

 in my code. when going to the logs, I see the entry, but I do not see that it is a warning, seems to be saved as any.  
This is my appsettings entry:

 "Serilog": {
    "Using": [ "Serilog.Sinks.GoogleCloudLogging" ],
    "MinimumLevel": "Warning",
    "WriteTo": [
      {
        "Name": "GoogleCloudLogging",
        "Args": {
          "projectID": "redacted",
          "useJsonOutput": "true",
          "resourceLabels": {
            "project_id": "redacted",
            "service_name": "api"
          },
          "labels": {
            "service": "api"
          }
        }
      }
    ]
  }

**Comment by manigandham** [comment]
Hi @bradsharp54 

Did you get this solved? Are you saying the logs are being recorded in Stackdriver but dont match the log level that you're using?

**Comment by manigandham** [comment]
I'm going to close this now since there's no reply. Feel free to re-open if you need help.
