### ISSUE TITLE
.NET Core logname beeing overwritten by "SourceContext"

### ISSUE THREAD

**Issue by W357** [manigandham/serilog-sinks-googlecloudlogging#3]
Logname of a log entry can be passed to the constructor of GoogleCloudLoggingSinkOptions, but is always overwritten by the "SourceContext" namespace:

```
if (property.Key.Equals("SourceContext", StringComparison.OrdinalIgnoreCase))
entry.LogName = new LogName(_sinkOptions.ProjectId, value).ToString();
```

**Comment by manigandham** [comment]
The `SourceContext` comes from Serilog or whatever logging abstraction you're using when you create a new logger with a specific context, so it's meant to overwrite the log name.

Can probably make a separate option to override...

**Comment by manigandham** [comment]
https://www.nuget.org/packages/Serilog.Sinks.GoogleCloudLogging/1.2.0

**Comment by W357** [comment]
Hey Mani.

Thank you. I think it makes sense to override. Having one log (instead of
having one for each namespace) makes it easier (at least for me) to read
the log.



2017-11-30 2:35 GMT+01:00 Mani Gandham <notifications@github.com>:
