### ISSUE TITLE
3.0.0 appears to be broken

### ISSUE THREAD

**Issue by provegard** [manigandham/serilog-sinks-googlecloudlogging#34]
I have to applications that use this library in the exact same way:

1. .NET Core 3.1, Serilog.Sinks.GoogleCloudLogging version 2.4.1
2. .NET Core 3.0, Serilog.Sinks.GoogleCloudLogging version 3.0.0

I can see the logs for application 1 in GCP, but there are no logs whatsoever for application 2.

Downgrading to version 2.4.1 in application 2 fixes the problem.

The options are very simple:

	var options = new GoogleCloudLoggingSinkOptions
	{
		UseJsonOutput = true,
		ServiceName = "myApp",
		ServiceVersion = "1.2.3.4
	};

Do I need any other configuration to make 3.0.0 work?

**Comment by manigandham** [comment]
The main changes in this library for 3.0.0 were updating the nuget references for `Google.Cloud.Logging.V2` to version 3.0.0 and `Serilog.Sinks.PeriodicBatching` to version 2.3.0

Can you download this repo and run the TestWeb project with your project settings? It's set to `netcore3.1` but you can switch to `netcore3.0` and see if that makes a difference? That's the fastest way to check if this is something with this library or your code.

**Comment by provegard** [comment]
Thanks, I will try it out today.

**Comment by manigandham** [comment]
@provegard Did you get this figured out?

**Comment by provegard** [comment]
Not yet. I have some time to test it today or tomorrow.

**Comment by provegard** [comment]
I can confirm that TestWeb works. I only tested locally though, whereas my application ran from inside a GKE cluster, so I need to do some more testing.

**Comment by provegard** [comment]
Minor:

I forgot to set project ID when testing my real application locally and got this:

```
Unhandled exception. System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at Google.Protobuf.Collections.MapField`2.get_Item(TKey key)
   at Serilog.Sinks.GoogleCloudLogging.GoogleCloudLoggingSink..ctor(GoogleCloudLoggingSinkOptions sinkOptions, MessageTemplateTextFormatter messageTemplateTextFormatter, Int32 batchSizeLimit, TimeSpan period)
```

This is the offending line:

      string projectId = this._sinkOptions.ProjectId ?? platform.ProjectId ?? this._resource.Labels["project_id"];

A better exception message would have been nice. :-)

**Comment by manigandham** [comment]
Sure, will add to the list of todos.

Are you using different service accounts for your apps? Do they both have the correct permissions to write logs?

**Comment by provegard** [comment]
Yes, different service accounts - both have the Logs Writer role. Version 2.4.1 works just fine.

Now I can see logs when running application 2 with 3.0.0 locally. 🎉 Next, I will try to figure out why it didn't work in GKE.

However, I stumbled across another obstacle when enabling StackDriver telemetry logging:

```
System.TypeLoadException: Could not load type 'Google.Api.Gax.Grpc.BackoffSettings' from assembly 'Google.Api.Gax.Grpc, Version=3.0.0.0, Culture=neutral, PublicKeyToken=3ec5ea7f18953e47'.
   at Google.Cloud.Trace.V2.TraceServiceSettings..ctor()
   at OpenTelemetry.Exporter.Stackdriver.StackdriverTraceExporter..ctor(String projectId)
```

This doesn't happen with 2.4.1, and installing Google.Api.Gax.Grpc 3.0.0 in the project that enables OpenTelemetry didn't work.

**Comment by manigandham** [comment]
There are a lot of issues with the Google cloud sdk releases. You might have to upgrade to the pre-release versions.

**Comment by provegard** [comment]
You're right, upgrading some Google libs helped. I still need to test in GKE though, will post back here once I've done that.

**Comment by manigandham** [comment]
Hey @provegard - do you still need help here or did it get resolved?

**Comment by manigandham** [comment]
Closing due to no reply

**Comment by provegard** [comment]
Apologies for not replying before. I haven't tested yet. Proper logging in Stackdriver has proven to be challenging, to say the least. When everything is stable, I'll give it a shot.

**Comment by manigandham** [comment]
I'm closing this now. Feel free to reopen once you have some testing results.

**Comment by provegard** [comment]
We've recently upgraded to 3.0.0 and it looks good. Must have been a conflict with another Google lib (which we don't use anymore).

**Comment by manigandham** [comment]
Sounds good, thanks for the update
