### ISSUE TITLE
Default True on UseSourceContextAsLogName

### ISSUE THREAD

**Issue by jimmystridh** [manigandham/serilog-sinks-googlecloudlogging#4]
Is this actually a reasonable default ?

serilog for asp.net core for example uses class names including namespaces as source contexts, so it will have values like Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker, which is a disallowed log name and will throw a
`Grpc.Core.RpcException: Status(StatusCode=InvalidArgument, Detail="Log name contains illegal character  ")` and will likely confuse new users.

**Comment by manigandham** [comment]
Is that the error you're getting? What character is disallowed? If it's the dot then I haven't run into that issue (see screenshot) but there might be something else in the grpc layer for the logging client.

![image](https://user-images.githubusercontent.com/457226/33667681-5acfde18-da52-11e7-8581-e385dd98de99.png)

**Comment by manigandham** [comment]
From the API docs: https://cloud.google.com/logging/docs/reference/v2/rest/v2/LogEntry

> [LOG_ID] must be URL-encoded within logName. Example: "organizations/1234567890/logs/cloudresourcemanager.googleapis.com%2Factivity". [LOG_ID] must be less than 512 characters long and can only include the following characters: **upper and lower case alphanumeric characters, forward-slash, underscore, hyphen, and period.**

**Comment by jimmystridh** [comment]
Ah, after looking deeper I found it's throwing for "Logger Factory" in the example code in https://github.com/manigandham/serilog-sinks-googlecloudlogging/blob/master/src/TestWeb/HomeController.cs#L22

**Comment by manigandham** [comment]
Got it, thanks for reporting that. I added some placeholder text but didn't realize it was broken by default. Will update and add some comments.

**Comment by manigandham** [comment]
Fixed in https://github.com/manigandham/serilog-sinks-googlecloudlogging/commit/0b9b2841f91891e710281a004a7b17e31940ba9e

**Comment by jimmystridh** [comment]
Looks good, thanks!
