### ISSUE TITLE
Suggestion: make it possible to omit 'special properties' from jsonPayload.Properties

### ISSUE THREAD

**Issue by pardahlman** [manigandham/serilog-sinks-googlecloudlogging#50]
I'm looking into using this sink to write data to Google Cloud Logging, and it looks promising - great work 👍 

When enabling `UseLogCorrelation` some properties are interpreted as [special properties](https://github.com/manigandham/serilog-sinks-googlecloudlogging/blob/master/src/Serilog.Sinks.GoogleCloudLogging/GoogleCloudLoggingSink.cs#L119) and assigned to corresponding properties on `LogEntry`. However, they are [always written as "normal" properties](https://github.com/manigandham/serilog-sinks-googlecloudlogging/blob/master/src/Serilog.Sinks.GoogleCloudLogging/GoogleCloudLoggingSink.cs#L111), too. I think it would make sense if they were omitted from `jsonPayload.Properties` to make the entry itself more concise.

This can be achieved either by automatically detect when a "special property" is handled and skip [writing it as a "normal" property](https://github.com/manigandham/serilog-sinks-googlecloudlogging/blob/master/src/Serilog.Sinks.GoogleCloudLogging/GoogleCloudLoggingSink.cs#L111), or by having a property on `GoogleCloudLoggingSinkOptions` to activate this behavior.

What are your thought on this?

**Comment by manigandham** [comment]
Hey @pardahlman Thanks for the contributions. 

For the log correlation, I left these properties in as they can be used to filter your logs directly in the log viewer without using the traces or when you export from GCP logging to other places (like storage buckets or BigQuery).

I would definitely recommend a new option to make this configurable but I don't think it's worth the extra complexity to save a few text fields, especially considering their usefulness and to avoid surprises of missing data. What do you think?

**Comment by pardahlman** [comment]
Thanks for the quick reply 🙏

> I left these properties in as they can be used to filter your logs directly in the log viewer without using the traces

It is possible to filter logs based on the `trace` or `spanId` by clicking on them in the log viewer and select _Show matching entries_ or by using a query (something like `trace="projects/projectid-123/traces/92d6c8215d3f7641a087d2a949a27bcc"`). I'm not sure I see the benefits of filtering based on custom properties with the same values?

As for exports, I do believe that the entire JSON is exported, in which case `trace` and `spanId` will be part of the data (although I can be wrong!).

I agree that it may be surprising if successfully interpreted "special properties" were omitted by default, perhaps the behavior should be something that the user have to configure explicitly? I'm ready to be persuaded that the feature brings too much complexity to the library, but I'm not convinced yet 😉

**Comment by pardahlman** [comment]
As a side note, wouldn't it be nice if this library in the future would have the capabilities to populate [all `LogEntry` properties](https://cloud.google.com/logging/docs/reference/v2/rest/v2/LogEntry) based on some convention? For example, if the Serilog `LogEvent` contained a property `HttpRequest` of type `Google.Cloud.Logging.Type.HttpRequest` it would be assigned to the `HttpRequest` property of the `LogEntry`.

In that future there would be a lot of duplicate properties (including non-scalar ones) logged both as typed property on the `LogEntry` as well as a label/JSON property if there wasn't a way to omit special properties 🤓

**Comment by manigandham** [comment]
Sure, the functionality sounds good. I still think it should be configurable so users can control how their data is output. 

Instead of adding yet another option, it might be best to refactor the `UseLogCorrelation` config into an enum value to switch between `extract` or `copy` custom properties to the LogEntry properties. It would be a breaking change but that would help draw attention to the setting too. Let me know what you think.

**Comment by pardahlman** [comment]
I agree, this feature should be configurable 👌 I'm thinking about naming; the concept "special properties" has never been exposed in any API (it is merely a name on a private method today). Is that a fine name, or should we call it something else? One suggestion is `LogEntryProperty`.

Next, should there be an `off` option, meaning no special properties should be extracted? I'm leaning against no, there is just too much upside populating properties on `LogEntry` - but there might be cases I'm not thinking of atm.

Another aspect is the level of configurability. Should it be possible to only treat some of the special properties as special. I was thinking along the lines of a flag enum containing all special properties. One thing I like with this idea is that the library exposes all "special properties" so the concept gets less abstract. On the other hand, it exposes an API surface that perhaps does not bring much value but needs to be maintained 🤔 I'm leaning against no at this point, perhaps such flag could be useful in the future.

**Comment by manigandham** [comment]
`Off` should definitely be an option. That's already an option today and I don't want to force any output on how logging works for users.

Off, copy, move are simple enough choices. I think we can keep it to just a single enum for now and add in a list of properties to manage at a future time. I'll leave the naming to you to start :)

**Comment by manigandham** [comment]
Hey @pardahlman  - still interested in this?
