### ISSUE TITLE
Is there any way to specify @type?

### ISSUE THREAD

**Issue by provegard** [manigandham/serilog-sinks-googlecloudlogging#59]
Hi!

We recently discovered a situation where error logs hadn't been detected by GCP Error Reporting. In the particular case, error messages were logged without an Exception, as there is no Exception associated with the error. Apparently this caused the errors to fly under Error Reporting's radar.

If I understand the [Error Reporting docs](https://cloud.google.com/error-reporting/docs/formatting-error-messages#formatting_requirements) correctly, it should be possible to set `@type` to `type.googleapis.com/google.devtools.clouderrorreporting.v1beta1.ReportedErrorEvent` to allow Error Reporting to detect an Exception-less error log.

Is there any way to set `@type` via this library?

Thank you!

**Comment by manigandham** [comment]
How were the errors logged? Was it through the MS logging or Serilog directly? Are you using the `LogError(exception, msg)` call? Can you provide a sample of the exact function call?

Cloud Logging looks for exceptions rather than just logs at the Error level and I'm not sure there is an easy way to change the type as part of the sink. The library only gets access to logs as they go through the Serilog pipeline and already checks the `Exception` field on the log event to handle formatting. Without that field populated it will require something else to signal an error.

Have you tried just creating a new Exception and using that? `logger.LogError(new Exception(msg), msg)`

**Comment by provegard** [comment]
> How were the errors logged? Was it through the MS logging or Serilog directly? Are you using the `LogError(exception, msg)` call? Can you provide a sample of the exact function call?

MS logging:

    _logger.LogError("Failed to ...");

Where `_logger` is `Microsoft.Extensions.Logging.ILogger`.

> Cloud Logging looks for exceptions rather than just logs at the Error level and I'm not sure there is an easy way to change the type as part of the sink. The library only gets access to logs as they go through the Serilog pipeline and already checks the `Exception` field on the log event to handle formatting. Without that field populated it will require something else to signal an error.

I'm not sure I follow - the error did show up in StackDriver Logging with severity=ERROR. It was just Error Reporting that didn't pick it up.
 
> Have you tried just creating a new Exception and using that? `logger.LogError(new Exception(msg), msg)`

I thought about it, but it feels like a hack and requires manually checking all places where exception-less errors are logged. But if there's no other way to solve the problem then that's what we have to do, of course.

**Comment by manigandham** [comment]
> I'm not sure I follow - the error did show up in StackDriver Logging with severity=ERROR. It was just Error Reporting that didn't pick it up.

Yes, what I meant is that GCP Error Reporting is separate from Cloud Logging and only [looks for a formatted exception message or the type field](https://cloud.google.com/error-reporting/docs/formatting-error-messages#log-entry-examples), not the severity level.

However without an `Exception` object attached, there's no way for the sink to know that this individual message should still be considered an exception and change the `type` field. 

The only way I can think of is to treat all severity=error messages as exception messages. This can't be the default but it's possible to make it a configurable option. I'll need to consider whether this adds too much confusion for users as this hasn't come up before.

In the short-term, I think adding a new `Exception` when you need to log a serious error would be the easiest, and most explicit way, to get those logs recognized by Error Reporting.

**Comment by manigandham** [comment]
After considering, the best option seems to be to just create a new `Exception` if you want specific issues and errors logged by and picked up with GCP Error Logging.

I've added some notes to the readme to highlight. Closing this now but let me know if you need anything else.
