### ISSUE TITLE
Credentials file in appsettings

### ISSUE THREAD

**Issue by MBleyerveld** [manigandham/serilog-sinks-googlecloudlogging#63]
Does anyone know how to set the credentials file in appsettings.json? Whenever we try to do it it fails parsing at the first letter of the filename. Maybe it's looking somewhere other than the project home folder?

e.g. using this appsettings snippet:
`      {
        "Name": "GoogleCloudLogging",
        "Args": {
          "projectID": "optii-keeper",
          "useJsonOutput": "true",
          "logName": "Optii.Pms.Api.Sms",
          "googleCredentialJson": "v2-gcp-logger_optii-keeper.json",
          "resourceType": "logging_log",
          "resourceLabels": {
            "project_id": "optii-keeper",
            "name": "pmsapidev.optii.net"
          }
        }
      }
`
we get this error:
`JsonReaderException: Unexpected character encountered while parsing value: v. Path '', line 0, position 0.`

**Comment by MBleyerveld** [comment]
OK i've found out that we have to specify a JSON string there not a filename. BUT I had to clone your repo and do some source diving to find out. The documentation needs to be clearer. Happy to update the readme and submit a PR.

**Comment by MBleyerveld** [comment]
Or I could have a go at actually allowing a filename to be specified, that's a bit larger scope though.

**Comment by MBleyerveld** [comment]
I have a branch and PR to make these changes if you are interested.

**Comment by manigandham** [comment]
Hey @MBleyerveld 

Most people use the Application Default Credentials, and the readme does specify in two places that the `GoogleCredentialJson` is the *contents* of the JSON file. 

https://github.com/manigandham/serilog-sinks-googlecloudlogging/blob/e2b608bb9ab48201ebe82c8675d8579ec9d0b19f/README.md?plain=1#L62

https://github.com/manigandham/serilog-sinks-googlecloudlogging/blob/e2b608bb9ab48201ebe82c8675d8579ec9d0b19f/README.md?plain=1#L84

If you have a clearer description then feel free to edit the docs. As for the allowing filenames though, I don't think that's worth the additional complexity since reading in a file is a 1-line statement.

**Comment by MBleyerveld** [comment]
Thanks for the reply @manigandham

The readme at line 84 is definitely ambiguous; it says what the option does but not how to do it. The line at 62 is better but still not absolutely clear. I have a branch & PR with changes but currently I'm unable to push back to github (I have no SSH key set up).

The 1-line thing about allowing a filename in appsettings sounds more like an argument FOR making the changes rather than against; I also have a branch & PR for that which I will push back when I am able; you can accept or refuse it as you like. You are correct about the simplicity; it was four lines in the main class (a new variable declaration and a multi-line ternary) plus a new property in the options class (and propagating the new option through the various parameter lists).

Thanks again for your time.

**Comment by manigandham** [comment]
Cool, happy to take any edits to make the readme clearer.

Also you can copy/paste your PR edits right here into github ( press "." to get to the web-based editor for the whole project).

**Comment by MBleyerveld** [comment]
I don't have permission to create a branch or PR for this repo. My proposed changes are as follows:
Line 62: `Set the GoogleCredentialJson config option to pass in a JSON string (the contents of your JSON credentials file).`
Line 84: `JSON string to override [Application Default Credentials](https://cloud.google.com/docs/authentication/production#providing_credentials_to_your_application) (contents of your credential file).`

**Comment by manigandham** [comment]
You have to fork the repo first, then create a branch with your changes, then submit a PR to merge them in. Here's the guide for Github: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

I'll edit the readme for now, thanks.
