### ISSUE TITLE
Stackdriver Resource Labels

### ISSUE THREAD

**Issue by jameskimsca** [manigandham/serilog-sinks-googlecloudlogging#8]
Hi,

So I've implemented the log as in the test project and hosted it on GCloud and it's logging fine except it's not populating the resource labels when I log an error.

It populates the labels when I log to the Console but not when I use Serilog to add an entry.

Do you know if this is a known issue with Serilog or is there something I'm not doing right?

I am using the latest version of Serilog.AspNetCore 2.1.1 and the GoogleCloudLogging 1.4.6.

Regards,

James

**Comment by manigandham** [comment]
What do you mean by resource labels?

**Comment by jameskimsca** [comment]
@manigandham here is a sample log:

 {
 insertId: "1fw4h35fnrpc7p"  
 jsonPayload: {
  message: "===> 2018-08-16 07:08:24.666 +00:00 [Error] (Thread Id: 7) (CapturedObject: DummyObjectModel { Name: "test", LoggedTime: 08/16/2018 07:08:24, Related: SubDummyObjectModel { Name: "related dummy" }, Arguments: [1234, "test", SubDummyObjectModel { Name: "embedded dummy" }, 76dc6dc3-6ea1-45d4-b3b3-0c27c5e9eab5] }) SeriStackPoc.CustomExceptions.SeriException: Exception of type 'SeriStackPoc.CustomExceptions.SeriException' was thrown.
"   
  properties: {
   ErrorObject: {
    Arguments: [
     0: 1234      
     1: "test"      
     2: {
      Name: "embedded dummy"       
     }
     3: "76dc6dc3-6ea1-45d4-b3b3-0c27c5e9eab5"      
    ]
    LoggedTime: "08/16/2018 07:08:24"     
    Name: "test"     
    Related: {
     Name: "related dummy"      
    }
   }
   Level: "Error"    
   StackTrace: ""    
   ThreadId: 7    
  }
 }
 labels: {
  cluster_name: "sca-dev-kube"   
  namespace_id: "default"   
 }
 logName: "projects/sca-dev-1/logs/seristackpoc"  
 receiveTimestamp: "2018-08-16T07:08:27.729212468Z"  
 resource: {
  labels: {
   cluster_name: ""    
   container_name: ""    
   instance_id: ""    
   namespace_id: ""    
   pod_id: ""    
   project_id: "sca-dev-1"    
   zone: ""    
  }
  type: "container"   
 }
 severity: "ERROR"  
 timestamp: "2018-08-16T07:08:24.666825700Z"  
}


Notice under resource -> labels, only the project id is set.

**Comment by manigandham** [comment]
@jameskimsca 

Got it. Here's the documentation on that: https://cloud.google.com/logging/docs/logs-based-metrics/labels#default_labels

> Resource labels: All metrics use a monitored resource object to identify the source of time series data. Each resource type includes a type name and one or more labels. Examples of types of resources include VM instances, CloudSQL databases, load balancers, etc.

If you're writing to the console while running on a GCE VM or GKE Container, then the StackDriver logging agents running on the server will capture that output and forward to the logging API, while automatically capturing source info like the Kubernetes labels you mention.

This Serilog sink writes directly to the logging API from your code so there's no context information to send other than the Project ID (which is required for the config anyway).

You can check this line here: https://github.com/manigandham/serilog-sinks-googlecloudlogging/blob/master/src/Serilog.Sinks.GoogleCloudLogging/GoogleCloudLoggingSink.cs#L30

The `MonitoredResource` class accepts `Labels` for additional info. That context info will have to be collected by your code explicitly, and these labels aren't currently exposed in the sink configuration so you'll have to build a version of your own. From a quick test, it doesn't seem like the labels are showing up in stackdriver though, might have to ask the GPC APIs team about it.

**Comment by jameskimsca** [comment]
@manigandham Right. Would you know how to retrieve the resource labels via the Google API?

**Comment by manigandham** [comment]
@jameskimsca are you all set here?

**Comment by jameskimsca** [comment]
@manigandham Yes thank you I'll close the issue.

**Comment by jameskimsca** [comment]
@manigandham I've created a PR to enable users to specify the mappings.

**Comment by jameskimsca** [comment]
Re-opening issue for pull request

**Comment by manigandham** [comment]
Added `ResourceLabels` as a config option in https://github.com/manigandham/serilog-sinks-googlecloudlogging/commit/ccb61f468d73b5906e1b2e98de7d29cd81d82da2

**Comment by manigandham** [comment]
https://www.nuget.org/packages/Serilog.Sinks.GoogleCloudLogging/1.4.7

Version 1.4.7 has been published. `ResourceLabels` is just another Dictionary<string, string>so you can pass in whatever you need to without coupling it to environment variables.

Let me know if that works for you.

**Comment by jameskimsca** [comment]
Hi @manigandham ,

I've checked out and have tested the code and it seems like it doesn't add new labels.
I have already left a comment in the commit but to add a new label we need to call _resource.Labels.Add method, the indexer only seems to update existing values.

**Comment by manigandham** [comment]
That's strange since it's the protobuf library class, in which the `Add` method just uses the indexer anyway:

https://github.com/protocolbuffers/protobuf/blob/master/csharp/src/Google.Protobuf/Collections/MapField.cs#L123

I'll test again

**Comment by manigandham** [comment]
@jameskimsca 

The labels are being sent to the logging API so the issue is most likely your config. What resource type did you pick? The labels are tied to the resource type, and the default `global` type does not accept any: https://cloud.google.com/logging/docs/api/v2/resource-list

**Comment by jameskimsca** [comment]
@manigandham we're using gke_container and it works when I use the code in my PR

**Comment by manigandham** [comment]
Do you mean `container` ? There is no `gke_container` listed on that page.

**Comment by manigandham** [comment]
Updating the sample to this works:

```
var sinkOptions = new GoogleCloudLoggingSinkOptions(GCP_PROJECT_ID, "container");
sinkOptions.ResourceLabels.Add("cluster_name", "the cluster name");
sinkOptions.ResourceLabels.Add("instance_id", "the instance id");
sinkOptions.ResourceLabels.Add("pod_id", "the pod id");

Log.Logger = new LoggerConfiguration()
    .WriteTo.GoogleCloudLogging(sinkOptions) // Add this to send Serilog output to GCP
    .MinimumLevel.Is(LogEventLevel.Verbose) // Serilog defaults to Info level and above, use this to override
    .CreateLogger();
```

![image](https://user-images.githubusercontent.com/457226/45340714-8b0fa380-b54c-11e8-8a53-d0edd214ff99.png)

**Comment by jameskimsca** [comment]
@manigandham it's listed here: [](https://cloud.google.com/monitoring/api/resources)
yes so it seems like the indexer isn't working as it's supposed to, hence, i had to add the if/else to call the add method

**Comment by manigandham** [comment]
That is a different API:

> The list of monitored resource types in Monitoring is not presently the same as the list of monitored resource types in Logging.

The indexer is not the issue because that's the only code path that assigns the variable, as you can see from the protobuf source code. You can also add a debug statement and see that labels being sent in the [WriteLogEntriesAsync](https://github.com/manigandham/serilog-sinks-googlecloudlogging/blob/master/src/Serilog.Sinks.GoogleCloudLogging/GoogleCloudLoggingSink.cs#L78) function. I also just posted a working example in the last comment so I'm not sure what to tell you here.

Double check your config and make sure it's the same between what you did in the PR and the latest release of this library, or upload your code sample here.

**Comment by jameskimsca** [comment]
@manigandham ah yes just realized to get the kubernetes instance, needed to get the information from environment variables

```
    var environmentValue = Environment.GetEnvironmentVariable(mappingItem.Key);
```

**Comment by manigandham** [comment]
Great, I'm going to consider this closed then.

**Comment by rockstardev** [comment]
@jameskimsca can you share how you've configured Kubernetes to pass environment variables to include everything (cluster_name, container_name, location, namespace_name, pod_name, project_id, ln-zap-212820)?

**Comment by manigandham** [comment]
Hey @rockstardev,

Check this previous comment in this thread: https://github.com/manigandham/serilog-sinks-googlecloudlogging/issues/8#issuecomment-414200581

**Comment by rockstardev** [comment]
Yeah, I've read through those links, but was hoping for concrete example because Downward API doesn't expose a lot of variables. Well, I guess it's up to fetching GCE Metadata... thanks for your response.
